CREATE TABLE "Task" (
	"TaskID"	INTEGER,
	"TaskTEXT"	TEXT,
	"TaskCOMP"	INTEGER,
	"TaskTIMECreate"	TEXT,
	"UserID"	INTEGER NOT NULL,
	PRIMARY KEY("TaskID"),
	FOREIGN KEY("UserID") REFERENCES "Users"("UserID")
);
CREATE TABLE "Users" (
	"UserID"	INTEGER,
	"UserNAME"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("UserID" AUTOINCREMENT)
);